[theme]
base = "light"
primaryColor = "#007A87"             # Blu petrolio per pulsanti/link
backgroundColor = "#EAF4F4"          # Bianco con tono azzurro
secondaryBackgroundColor = "#FFFFFF" # Box e card
textColor = "#1E272E"                # Testo grigio-nero profondo
font = "sans serif"
