[theme]
base = "light"
primaryColor = "#D4AF7F"             # Oro tenue
backgroundColor = "#F4F1EA"          # Avorio chiaro
secondaryBackgroundColor = "#FFFFFF" # Box chiari
textColor = "#2C2C2C"                # Testo neutro scuro
font = "serif"
